(load-file "~/.emacs.d/js-doc.el")
(require 'js-doc)
(add-hook 'js2-mode-hook
          #'(lambda ()
              (define-key js2-mode-map "\C-ci" 'js-doc-insert-function-doc)
              (define-key js2-mode-map "@" 'js-doc-insert-tag)))
(setq js-indent-level 2)
(setq js2-basic-offset 2)
(setq js2-include-node-externs t)
(add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
;(set-face-attribute 'js2-error nil :background "red" :foreground "black" :weight 'bold)
;(set-face-attribute 'js2-external-variable nil :background "orange" :foreground "black" :weight 'bold)
