-- This file has been generated by /usr/local/bin/notion. Do not edit.
return {
    ["date"] = {
        ["date_format"] = "%a %d.%m.%Y %H:%M",
    },
    ["mail"] = {
    },
    ["mpd"] = {
        ["template"] = "%artist_or_album - %title",
    },
    ["load"] = {
    },
    ["weather"] = {
    },
}

