-- This file has been generated by /usr/local/bin/notion. Do not edit.
return {
    [1] = "menu.mainmenu:session/restart",
    [2] = "run:firefox",
    [3] = "run:shutter",
    [4] = "run:ั\139ั\128ะณะตะตั\131ะบ",
    [5] = "run:corebird",
    [6] = "run:plaidchat",
    [7] = "run:gvimd",
    [8] = "run:google-chrome-unstable",
    [9] = "run:lxterminal",
    [10] = "run:Eterm",
    [11] = "run:eterm",
    [12] = "windowname:Notion keyboard reference - Google Chrome",
    [13] = "run:terminology",
    [14] = "run:sakura",
    [15] = "run:saku",
    [16] = "run:cssh ansible@online4{1,2,3}.{m,d,n}1.nato",
    [17] = "workspacelayout:",
    [18] = "workspacename:prod_srv",
}

