-- This file has been generated by notion. Do not edit.
return {
    [1] = {
        ["type"] = "WScreen",
        ["name"] = "WScreen<1>",
        ["managed"] = {
            [1] = {
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<1>",
                        ["bottom"] = true,
                        ["split_tree"] = {
                            ["type"] = "WSplitSplit",
                            ["tls"] = 1693,0,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["windowid"] = 31457281,0,
                                                    ["bottom"] = true,
                                                    ["checkcode"] = 4,0,
                                                    ["geom"] = {
                                                        ["w"] = 1691,0,
                                                        ["h"] = 1419,0,
                                                        ["y"] = 0,0,
                                                        ["x"] = 0,0,
                                                    },
                                                    ["level"] = 0,0,
                                                    ["type"] = "WClientWin",
                                                },
                                            },
                                            ["name"] = "WGroupCW<1>",
                                            ["geom"] = {
                                                ["w"] = 1691,0,
                                                ["h"] = 1419,0,
                                                ["y"] = 20,0,
                                                ["x"] = 1,0,
                                            },
                                            ["sizepolicy"] = "full",
                                            ["switchto"] = true,
                                            ["level"] = 0,0,
                                            ["type"] = "WGroupCW",
                                        },
                                    },
                                    ["type"] = "WFrame",
                                    ["name"] = "Tiling Frame<1>",
                                    ["mode"] = 1,0,
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["br"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["windowid"] = 6291459,0,
                                                    ["bottom"] = true,
                                                    ["checkcode"] = 5,0,
                                                    ["geom"] = {
                                                        ["w"] = 1745,0,
                                                        ["h"] = 1419,0,
                                                        ["y"] = 0,0,
                                                        ["x"] = 0,0,
                                                    },
                                                    ["level"] = 0,0,
                                                    ["type"] = "WClientWin",
                                                },
                                            },
                                            ["name"] = "WGroupCW",
                                            ["hidden"] = true,
                                            ["sizepolicy"] = "full",
                                            ["geom"] = {
                                                ["w"] = 1745,0,
                                                ["h"] = 1419,0,
                                                ["y"] = 20,0,
                                                ["x"] = 1,0,
                                            },
                                            ["level"] = 0,0,
                                            ["type"] = "WGroupCW",
                                        },
                                        [2] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["windowid"] = 65011715,0,
                                                    ["bottom"] = true,
                                                    ["checkcode"] = 6,0,
                                                    ["geom"] = {
                                                        ["w"] = 1745,0,
                                                        ["h"] = 1419,0,
                                                        ["y"] = 0,0,
                                                        ["x"] = 0,0,
                                                    },
                                                    ["level"] = 0,0,
                                                    ["type"] = "WClientWin",
                                                },
                                            },
                                            ["name"] = "WGroupCW<3>",
                                            ["geom"] = {
                                                ["w"] = 1745,0,
                                                ["h"] = 1419,0,
                                                ["y"] = 20,0,
                                                ["x"] = 1,0,
                                            },
                                            ["sizepolicy"] = "full",
                                            ["switchto"] = true,
                                            ["level"] = 0,0,
                                            ["type"] = "WGroupCW",
                                        },
                                    },
                                    ["type"] = "WFrame",
                                    ["name"] = "Tiling Frame<2>",
                                    ["mode"] = 1,0,
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["brs"] = 1747,0,
                            ["dir"] = "horizontal",
                        },
                        ["geom"] = {
                            ["w"] = 3440,0,
                            ["h"] = 1440,0,
                            ["y"] = 0,0,
                            ["x"] = 0,0,
                        },
                        ["level"] = 0,0,
                        ["type"] = "WTiling",
                    },
                },
                ["name"] = "WGroupWS<3>",
                ["initial_outputs"] = {
                    [1] = "DP-1",
                },
                ["sizepolicy"] = "full",
                ["switchto"] = true,
                ["level"] = 0,0,
                ["type"] = "WGroupWS",
            },
            [2] = {
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<3>",
                        ["bottom"] = true,
                        ["split_tree"] = {
                            ["type"] = "WSplitSplit",
                            ["tls"] = 1720,0,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["windowid"] = 69206017,0,
                                                    ["bottom"] = true,
                                                    ["checkcode"] = 7,0,
                                                    ["geom"] = {
                                                        ["w"] = 1718,0,
                                                        ["h"] = 1419,0,
                                                        ["y"] = 0,0,
                                                        ["x"] = 0,0,
                                                    },
                                                    ["level"] = 0,0,
                                                    ["type"] = "WClientWin",
                                                },
                                            },
                                            ["name"] = "WGroupCW<4>",
                                            ["geom"] = {
                                                ["w"] = 1718,0,
                                                ["h"] = 1419,0,
                                                ["y"] = 20,0,
                                                ["x"] = 1,0,
                                            },
                                            ["sizepolicy"] = "full",
                                            ["switchto"] = true,
                                            ["level"] = 0,0,
                                            ["type"] = "WGroupCW",
                                        },
                                    },
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<4>",
                                    ["mode"] = 1,0,
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["br"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["windowid"] = 69206024,0,
                                                    ["bottom"] = true,
                                                    ["checkcode"] = 8,0,
                                                    ["geom"] = {
                                                        ["w"] = 1718,0,
                                                        ["h"] = 1419,0,
                                                        ["y"] = 0,0,
                                                        ["x"] = 0,0,
                                                    },
                                                    ["level"] = 0,0,
                                                    ["type"] = "WClientWin",
                                                },
                                            },
                                            ["name"] = "WGroupCW<5>",
                                            ["geom"] = {
                                                ["w"] = 1718,0,
                                                ["h"] = 1419,0,
                                                ["y"] = 20,0,
                                                ["x"] = 1,0,
                                            },
                                            ["sizepolicy"] = "full",
                                            ["switchto"] = true,
                                            ["level"] = 0,0,
                                            ["type"] = "WGroupCW",
                                        },
                                    },
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<5>",
                                    ["mode"] = 1,0,
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["brs"] = 1720,0,
                            ["dir"] = "horizontal",
                        },
                        ["geom"] = {
                            ["w"] = 3440,0,
                            ["h"] = 1440,0,
                            ["y"] = 0,0,
                            ["x"] = 0,0,
                        },
                        ["level"] = 0,0,
                        ["type"] = "WTiling",
                    },
                },
                ["name"] = "WGroupWS<4>",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DP-1",
                },
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 0,0,
                ["type"] = "WGroupWS",
            },
            [3] = {
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 1,0,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*",
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 480,0,
                            ["x"] = 1400,0,
                        },
                        ["level"] = 1024,0,
                        ["mode"] = 0,0,
                    },
                },
            },
            [4] = {
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 1,0,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*<2>",
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<2>",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 480,0,
                            ["x"] = 1400,0,
                        },
                        ["level"] = 1024,0,
                        ["mode"] = 0,0,
                    },
                },
            },
            [5] = {
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 1,0,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*<3>",
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<3>",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 480,0,
                            ["x"] = 1400,0,
                        },
                        ["level"] = 1024,0,
                        ["mode"] = 0,0,
                    },
                },
            },
            [6] = {
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 1,0,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*<4>",
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<4>",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 480,0,
                            ["x"] = 1400,0,
                        },
                        ["level"] = 1024,0,
                        ["mode"] = 0,0,
                    },
                },
            },
            [7] = {
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 1,0,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*<5>",
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<5>",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 300,0,
                            ["x"] = 640,0,
                        },
                        ["level"] = 1024,0,
                        ["mode"] = 0,0,
                    },
                },
            },
            [8] = {
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 1,0,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*<6>",
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<6>",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 480,0,
                            ["x"] = 2800,0,
                        },
                        ["level"] = 1024,0,
                        ["mode"] = 0,0,
                    },
                },
            },
            [9] = {
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 1,0,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*<7>",
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<7>",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 480,0,
                            ["x"] = 2800,0,
                        },
                        ["level"] = 1024,0,
                        ["mode"] = 0,0,
                    },
                },
            },
            [10] = {
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 1,0,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*<8>",
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<8>",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 480,0,
                            ["x"] = 2800,0,
                        },
                        ["level"] = 1024,0,
                        ["mode"] = 0,0,
                    },
                },
            },
            [11] = {
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 1,0,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*<9>",
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<9>",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 480,0,
                            ["x"] = 2800,0,
                        },
                        ["level"] = 1024,0,
                        ["mode"] = 0,0,
                    },
                },
            },
            [12] = {
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 1,0,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*<10>",
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<10>",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 480,0,
                            ["x"] = 2800,0,
                        },
                        ["level"] = 1024,0,
                        ["mode"] = 0,0,
                    },
                },
            },
            [13] = {
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 1,0,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*<11>",
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<11>",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 480,0,
                            ["x"] = 2800,0,
                        },
                        ["level"] = 1024,0,
                        ["mode"] = 0,0,
                    },
                },
            },
            [14] = {
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 1,0,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*<12>",
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<12>",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 480,0,
                            ["x"] = 2800,0,
                        },
                        ["level"] = 1024,0,
                        ["mode"] = 0,0,
                    },
                },
            },
            [15] = {
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 1,0,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*<13>",
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<13>",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 480,0,
                            ["x"] = 2800,0,
                        },
                        ["level"] = 1024,0,
                        ["mode"] = 0,0,
                    },
                },
            },
            [16] = {
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 1,0,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*<14>",
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<14>",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 480,0,
                            ["x"] = 2800,0,
                        },
                        ["level"] = 1024,0,
                        ["mode"] = 0,0,
                    },
                },
            },
            [17] = {
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 1,0,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*<15>",
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<15>",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 300,0,
                            ["x"] = 640,0,
                        },
                        ["level"] = 1024,0,
                        ["mode"] = 0,0,
                    },
                },
            },
            [18] = {
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 3440,0,
                    ["h"] = 1440,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 1,0,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*<16>",
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<16>",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 480,0,
                            ["x"] = 2800,0,
                        },
                        ["level"] = 1024,0,
                        ["mode"] = 0,0,
                    },
                },
            },
        },
    },
    [0] = {
        ["type"] = "WScreen",
        ["name"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<2>",
                        ["bottom"] = true,
                        ["split_tree"] = {
                            ["type"] = "WSplitSplit",
                            ["tls"] = 1078,0,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["name"] = "Framed PHolder Frame",
                                    ["saved_h"] = 462,0,
                                    ["saved_y"] = 204,0,
                                    ["managed"] = {
                                    },
                                    ["mode"] = 1,0,
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["brs"] = 2,0,
                            ["dir"] = "vertical",
                        },
                        ["geom"] = {
                            ["w"] = 1920,0,
                            ["h"] = 1080,0,
                            ["y"] = 0,0,
                            ["x"] = 0,0,
                        },
                        ["level"] = 0,0,
                        ["type"] = "WTiling",
                    },
                },
                ["name"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "eDP-1",
                },
                ["geom"] = {
                    ["w"] = 1920,0,
                    ["h"] = 1080,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 0,0,
                ["type"] = "WGroupWS",
            },
            [2] = {
                ["geom"] = {
                    ["w"] = 1920,0,
                    ["h"] = 1080,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["split_tree"] = {
                            ["type"] = "WSplitSplit",
                            ["tls"] = 1044,0,
                            ["tl"] = {
                                ["type"] = "WSplitSplit",
                                ["tls"] = 958,0,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                            [1] = {
                                                ["managed"] = {
                                                    [1] = {
                                                        ["sizepolicy"] = "full",
                                                        ["windowid"] = 56623107,0,
                                                        ["bottom"] = true,
                                                        ["checkcode"] = 1,0,
                                                        ["geom"] = {
                                                            ["w"] = 956,0,
                                                            ["h"] = 1023,0,
                                                            ["y"] = 0,0,
                                                            ["x"] = 0,0,
                                                        },
                                                        ["level"] = 0,0,
                                                        ["type"] = "WClientWin",
                                                    },
                                                },
                                                ["name"] = "WGroupCW<2>",
                                                ["geom"] = {
                                                    ["w"] = 956,0,
                                                    ["h"] = 1023,0,
                                                    ["y"] = 20,0,
                                                    ["x"] = 1,0,
                                                },
                                                ["sizepolicy"] = "full",
                                                ["switchto"] = true,
                                                ["level"] = 0,0,
                                                ["type"] = "WGroupCW",
                                            },
                                        },
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame",
                                        ["mode"] = 1,0,
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["br"] = {
                                    ["type"] = "WSplitSplit",
                                    ["tls"] = 809,0,
                                    ["tl"] = {
                                        ["regparams"] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["sizepolicy"] = "full",
                                                            ["windowid"] = 79691779,0,
                                                            ["bottom"] = true,
                                                            ["checkcode"] = 2,0,
                                                            ["geom"] = {
                                                                ["w"] = 960,0,
                                                                ["h"] = 788,0,
                                                                ["y"] = 0,0,
                                                                ["x"] = 0,0,
                                                            },
                                                            ["level"] = 0,0,
                                                            ["type"] = "WClientWin",
                                                        },
                                                    },
                                                    ["name"] = "WGroupCW<6>",
                                                    ["geom"] = {
                                                        ["w"] = 960,0,
                                                        ["h"] = 788,0,
                                                        ["y"] = 20,0,
                                                        ["x"] = 1,0,
                                                    },
                                                    ["sizepolicy"] = "full",
                                                    ["switchto"] = true,
                                                    ["level"] = 0,0,
                                                    ["type"] = "WGroupCW",
                                                },
                                            },
                                            ["type"] = "WFrame",
                                            ["name"] = "Tiling Frame",
                                            ["mode"] = 1,0,
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["br"] = {
                                        ["regparams"] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["sizepolicy"] = "full",
                                                            ["windowid"] = 81788931,0,
                                                            ["bottom"] = true,
                                                            ["checkcode"] = 3,0,
                                                            ["geom"] = {
                                                                ["w"] = 960,0,
                                                                ["h"] = 214,0,
                                                                ["y"] = 0,0,
                                                                ["x"] = 0,0,
                                                            },
                                                            ["level"] = 0,0,
                                                            ["type"] = "WClientWin",
                                                        },
                                                    },
                                                    ["name"] = "WGroupCW<7>",
                                                    ["geom"] = {
                                                        ["w"] = 960,0,
                                                        ["h"] = 214,0,
                                                        ["y"] = 20,0,
                                                        ["x"] = 1,0,
                                                    },
                                                    ["sizepolicy"] = "full",
                                                    ["switchto"] = true,
                                                    ["level"] = 0,0,
                                                    ["type"] = "WGroupCW",
                                                },
                                            },
                                            ["type"] = "WFrame",
                                            ["name"] = "Tiling Frame<3>",
                                            ["mode"] = 1,0,
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["brs"] = 235,0,
                                    ["dir"] = "vertical",
                                },
                                ["brs"] = 962,0,
                                ["dir"] = "horizontal",
                            },
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["brs"] = 36,0,
                            ["dir"] = "vertical",
                        },
                        ["geom"] = {
                            ["w"] = 1920,0,
                            ["h"] = 1080,0,
                            ["y"] = 0,0,
                            ["x"] = 0,0,
                        },
                        ["level"] = 0,0,
                        ["type"] = "WTiling",
                    },
                },
                ["name"] = "WGroupWS<2>",
                ["initial_outputs"] = {
                    [1] = "eDP-1",
                },
                ["sizepolicy"] = "full",
                ["switchto"] = true,
                ["level"] = 0,0,
                ["type"] = "WGroupWS",
            },
            [3] = {
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 1920,0,
                    ["h"] = 1080,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["level"] = 1,0,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*<1>",
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<1>",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 300,0,
                            ["x"] = 640,0,
                        },
                        ["level"] = 1024,0,
                        ["mode"] = 0,0,
                    },
                },
            },
        },
    },
}

