-- This file has been generated by /usr/local/bin/notion. Do not edit.
return {
    [1] = "menu.mainmenu:session/restart",
    [2] = "run:terminology",
    [3] = "run:sakura",
    [4] = "run:saku",
    [5] = "run:gvimd",
    [6] = "run:cssh ansible@online4{1,2,3}.{m,d,n}1.nato",
    [7] = "workspacelayout:",
    [8] = "workspacename:prod_srv",
    [9] = "run:google-chrome-unstable",
    [10] = "run:corebird",
    [11] = "run:plaidchat",
}

