-- This file has been generated by /usr/local/bin/notion. Do not edit.
return {
    [1] = {
        ["managed"] = {
            [1] = {
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["initial_outputs"] = {
                    [1] = "VGA1",
                },
                ["sizepolicy"] = "full",
                ["level"] = 0,0,
                ["switchto"] = true,
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["w"] = 1600,0,
                            ["h"] = 1200,0,
                            ["y"] = 0,0,
                            ["x"] = 0,0,
                        },
                        ["level"] = 0,0,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["mode"] = 1,0,
                                ["managed"] = {
                                    [1] = {
                                        ["geom"] = {
                                            ["w"] = 1598,0,
                                            ["h"] = 1181,0,
                                            ["y"] = 18,0,
                                            ["x"] = 1,0,
                                        },
                                        ["level"] = 0,0,
                                        ["sizepolicy"] = "full",
                                        ["switchto"] = true,
                                        ["managed"] = {
                                            [1] = {
                                                ["geom"] = {
                                                    ["w"] = 1598,0,
                                                    ["h"] = 1181,0,
                                                    ["y"] = 0,0,
                                                    ["x"] = 0,0,
                                                },
                                                ["level"] = 1,0,
                                                ["sizepolicy"] = "full",
                                                ["windowid"] = 6291457,0,
                                                ["bottom"] = true,
                                                ["type"] = "WClientWin",
                                                ["checkcode"] = 5,0,
                                            },
                                        },
                                        ["type"] = "WGroupCW",
                                        ["name"] = "WGroupCW",
                                    },
                                    [2] = {
                                        ["geom"] = {
                                            ["w"] = 1598,0,
                                            ["h"] = 1181,0,
                                            ["y"] = 18,0,
                                            ["x"] = 1,0,
                                        },
                                        ["level"] = 0,0,
                                        ["sizepolicy"] = "full",
                                        ["hidden"] = true,
                                        ["managed"] = {
                                            [1] = {
                                                ["geom"] = {
                                                    ["w"] = 1598,0,
                                                    ["h"] = 1181,0,
                                                    ["y"] = 0,0,
                                                    ["x"] = 0,0,
                                                },
                                                ["level"] = 1,0,
                                                ["sizepolicy"] = "full",
                                                ["windowid"] = 6291535,0,
                                                ["bottom"] = true,
                                                ["type"] = "WClientWin",
                                                ["checkcode"] = 6,0,
                                            },
                                        },
                                        ["type"] = "WGroupCW",
                                        ["name"] = "WGroupCW<2>",
                                    },
                                },
                                ["type"] = "WFrame",
                                ["name"] = "WFrame<6>",
                            },
                        },
                        ["bottom"] = true,
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<3>",
                    },
                },
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS<3>",
            },
            [2] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 360,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                    },
                },
            },
            [3] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<2>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 360,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<2>",
                    },
                },
            },
            [4] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<3>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 360,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<3>",
                    },
                },
            },
            [5] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<4>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 360,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<4>",
                    },
                },
            },
            [6] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<5>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 360,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<5>",
                    },
                },
            },
            [7] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<6>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 360,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<6>",
                    },
                },
            },
            [8] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<7>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 360,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<7>",
                    },
                },
            },
            [9] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<8>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 360,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<8>",
                    },
                },
            },
            [10] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<9>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 360,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<9>",
                    },
                },
            },
            [11] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<10>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 360,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<10>",
                    },
                },
            },
            [12] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<11>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 360,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<11>",
                    },
                },
            },
            [13] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<12>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 360,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<12>",
                    },
                },
            },
            [14] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<13>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 360,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<13>",
                    },
                },
            },
            [15] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<14>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 360,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<14>",
                    },
                },
            },
            [16] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<15>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 360,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<15>",
                    },
                },
            },
        },
        ["type"] = "WScreen",
        ["name"] = "WScreen<1>",
    },
    [2] = {
        ["managed"] = {
            [1] = {
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
                ["sizepolicy"] = "full",
                ["level"] = 0,0,
                ["switchto"] = true,
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["w"] = 1600,0,
                            ["h"] = 900,0,
                            ["y"] = 0,0,
                            ["x"] = 0,0,
                        },
                        ["level"] = 0,0,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["br"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["mode"] = 1,0,
                                    ["managed"] = {
                                        [1] = {
                                            ["geom"] = {
                                                ["w"] = 514,0,
                                                ["h"] = 881,0,
                                                ["y"] = 18,0,
                                                ["x"] = 1,0,
                                            },
                                            ["level"] = 0,0,
                                            ["sizepolicy"] = "full",
                                            ["switchto"] = true,
                                            ["managed"] = {
                                                [1] = {
                                                    ["geom"] = {
                                                        ["w"] = 514,0,
                                                        ["h"] = 881,0,
                                                        ["y"] = 0,0,
                                                        ["x"] = 0,0,
                                                    },
                                                    ["level"] = 1,0,
                                                    ["sizepolicy"] = "full",
                                                    ["windowid"] = 20971529,0,
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["checkcode"] = 8,0,
                                                },
                                            },
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW<3>",
                                        },
                                    },
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<5>",
                                },
                            },
                            ["brs"] = 516,0,
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["mode"] = 1,0,
                                    ["managed"] = {
                                        [1] = {
                                            ["geom"] = {
                                                ["w"] = 1082,0,
                                                ["h"] = 881,0,
                                                ["y"] = 18,0,
                                                ["x"] = 1,0,
                                            },
                                            ["level"] = 0,0,
                                            ["sizepolicy"] = "full",
                                            ["switchto"] = true,
                                            ["managed"] = {
                                                [1] = {
                                                    ["geom"] = {
                                                        ["w"] = 1082,0,
                                                        ["h"] = 881,0,
                                                        ["y"] = 0,0,
                                                        ["x"] = 0,0,
                                                    },
                                                    ["level"] = 1,0,
                                                    ["sizepolicy"] = "full",
                                                    ["windowid"] = 14680065,0,
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["checkcode"] = 7,0,
                                                },
                                            },
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW<1>",
                                        },
                                    },
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<4>",
                                },
                            },
                            ["tls"] = 1084,0,
                            ["type"] = "WSplitSplit",
                            ["dir"] = "horizontal",
                        },
                        ["bottom"] = true,
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<2>",
                    },
                },
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS<2>",
            },
            [2] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<1>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<1>",
                    },
                },
            },
            [3] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<16>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<16>",
                    },
                },
            },
            [4] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<17>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<17>",
                    },
                },
            },
            [5] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<18>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<18>",
                    },
                },
            },
            [6] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<19>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<19>",
                    },
                },
            },
            [7] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<20>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<20>",
                    },
                },
            },
            [8] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<21>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<21>",
                    },
                },
            },
            [9] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<22>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<22>",
                    },
                },
            },
            [10] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<23>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<23>",
                    },
                },
            },
            [11] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<24>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<24>",
                    },
                },
            },
            [12] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<25>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<25>",
                    },
                },
            },
            [13] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<26>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<26>",
                    },
                },
            },
            [14] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<27>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<27>",
                    },
                },
            },
            [15] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<29>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<29>",
                    },
                },
            },
            [16] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<30>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<30>",
                    },
                },
            },
            [17] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<31>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<31>",
                    },
                },
            },
            [18] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<32>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<32>",
                    },
                },
            },
            [19] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<33>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<33>",
                    },
                },
            },
            [20] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<34>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<34>",
                    },
                },
            },
            [21] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<35>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<35>",
                    },
                },
            },
            [22] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<36>",
                ["geom"] = {
                    ["w"] = 1600,0,
                    ["h"] = 900,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 210,0,
                            ["x"] = 480,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<36>",
                    },
                },
            },
        },
        ["type"] = "WScreen",
        ["name"] = "WScreen<2>",
    },
    [0] = {
        ["managed"] = {
            [1] = {
                ["geom"] = {
                    ["w"] = 1920,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["initial_outputs"] = {
                    [1] = "HDMI1",
                },
                ["sizepolicy"] = "full",
                ["level"] = 0,0,
                ["switchto"] = true,
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["w"] = 1920,0,
                            ["h"] = 1200,0,
                            ["y"] = 0,0,
                            ["x"] = 0,0,
                        },
                        ["level"] = 0,0,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["brs"] = 15,0,
                            ["tl"] = {
                                ["br"] = {
                                    ["br"] = {
                                        ["type"] = "WSplitRegion",
                                        ["regparams"] = {
                                            ["mode"] = 1,0,
                                            ["managed"] = {
                                                [1] = {
                                                    ["geom"] = {
                                                        ["w"] = 946,0,
                                                        ["h"] = 156,0,
                                                        ["y"] = 18,0,
                                                        ["x"] = 1,0,
                                                    },
                                                    ["level"] = 0,0,
                                                    ["sizepolicy"] = "full",
                                                    ["switchto"] = true,
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["geom"] = {
                                                                ["w"] = 946,0,
                                                                ["h"] = 156,0,
                                                                ["y"] = 0,0,
                                                                ["x"] = 0,0,
                                                            },
                                                            ["level"] = 1,0,
                                                            ["sizepolicy"] = "full",
                                                            ["windowid"] = 31457282,0,
                                                            ["bottom"] = true,
                                                            ["type"] = "WClientWin",
                                                            ["checkcode"] = 3,0,
                                                        },
                                                    },
                                                    ["type"] = "WGroupCW",
                                                    ["name"] = "WGroupCW<6>",
                                                },
                                            },
                                            ["type"] = "WFrame",
                                            ["name"] = "Tiling Frame<2>",
                                        },
                                    },
                                    ["brs"] = 948,0,
                                    ["tl"] = {
                                        ["type"] = "WSplitRegion",
                                        ["regparams"] = {
                                            ["mode"] = 1,0,
                                            ["managed"] = {
                                                [1] = {
                                                    ["geom"] = {
                                                        ["w"] = 970,0,
                                                        ["h"] = 156,0,
                                                        ["y"] = 18,0,
                                                        ["x"] = 1,0,
                                                    },
                                                    ["level"] = 0,0,
                                                    ["sizepolicy"] = "full",
                                                    ["switchto"] = true,
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["geom"] = {
                                                                ["w"] = 970,0,
                                                                ["h"] = 156,0,
                                                                ["y"] = 0,0,
                                                                ["x"] = 0,0,
                                                            },
                                                            ["level"] = 1,0,
                                                            ["sizepolicy"] = "full",
                                                            ["windowid"] = 29360130,0,
                                                            ["bottom"] = true,
                                                            ["type"] = "WClientWin",
                                                            ["checkcode"] = 2,0,
                                                        },
                                                    },
                                                    ["type"] = "WGroupCW",
                                                    ["name"] = "WGroupCW<5>",
                                                },
                                            },
                                            ["type"] = "WFrame",
                                            ["name"] = "Tiling Frame<1>",
                                        },
                                    },
                                    ["tls"] = 972,0,
                                    ["type"] = "WSplitSplit",
                                    ["dir"] = "horizontal",
                                },
                                ["brs"] = 175,0,
                                ["tl"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["mode"] = 1,0,
                                        ["managed"] = {
                                            [1] = {
                                                ["geom"] = {
                                                    ["w"] = 1918,0,
                                                    ["h"] = 991,0,
                                                    ["y"] = 18,0,
                                                    ["x"] = 1,0,
                                                },
                                                ["level"] = 0,0,
                                                ["sizepolicy"] = "full",
                                                ["switchto"] = true,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["geom"] = {
                                                            ["w"] = 1916,0,
                                                            ["h"] = 985,0,
                                                            ["y"] = 3,0,
                                                            ["x"] = 1,0,
                                                        },
                                                        ["level"] = 1,0,
                                                        ["sizepolicy"] = "full",
                                                        ["windowid"] = 27262979,0,
                                                        ["bottom"] = true,
                                                        ["type"] = "WClientWin",
                                                        ["checkcode"] = 1,0,
                                                    },
                                                },
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<4>",
                                            },
                                        },
                                        ["type"] = "WFrame",
                                        ["name"] = "Tiling Frame",
                                    },
                                },
                                ["tls"] = 1010,0,
                                ["type"] = "WSplitSplit",
                                ["dir"] = "vertical",
                            },
                            ["tls"] = 1185,0,
                            ["type"] = "WSplitSplit",
                            ["dir"] = "vertical",
                        },
                        ["bottom"] = true,
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                    },
                },
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS",
            },
            [2] = {
                ["geom"] = {
                    ["w"] = 1920,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["initial_outputs"] = {
                    [1] = "HDMI1",
                },
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["level"] = 0,0,
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["w"] = 1920,0,
                            ["h"] = 1200,0,
                            ["y"] = 0,0,
                            ["x"] = 0,0,
                        },
                        ["level"] = 0,0,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["brs"] = 15,0,
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["mode"] = 1,0,
                                    ["managed"] = {
                                        [1] = {
                                            ["geom"] = {
                                                ["w"] = 1918,0,
                                                ["h"] = 1166,0,
                                                ["y"] = 18,0,
                                                ["x"] = 1,0,
                                            },
                                            ["level"] = 0,0,
                                            ["sizepolicy"] = "full",
                                            ["switchto"] = true,
                                            ["managed"] = {
                                                [1] = {
                                                    ["geom"] = {
                                                        ["w"] = 1914,0,
                                                        ["h"] = 1164,0,
                                                        ["y"] = 1,0,
                                                        ["x"] = 2,0,
                                                    },
                                                    ["level"] = 1,0,
                                                    ["sizepolicy"] = "full",
                                                    ["windowid"] = 35651586,0,
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["checkcode"] = 4,0,
                                                },
                                            },
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW<8>",
                                        },
                                    },
                                    ["type"] = "WFrame",
                                    ["name"] = "Tiling Frame<5>",
                                },
                            },
                            ["tls"] = 1185,0,
                            ["type"] = "WSplitSplit",
                            ["dir"] = "vertical",
                        },
                        ["bottom"] = true,
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<1>",
                    },
                },
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS<1>",
            },
            [3] = {
                ["geom"] = {
                    ["w"] = 1920,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["initial_outputs"] = {
                    [1] = "HDMI1",
                },
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["level"] = 0,0,
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["w"] = 1920,0,
                            ["h"] = 1200,0,
                            ["y"] = 0,0,
                            ["x"] = 0,0,
                        },
                        ["level"] = 0,0,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["br"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["mode"] = 1,0,
                                    ["managed"] = {
                                    },
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<1>",
                                },
                            },
                            ["brs"] = 960,0,
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["mode"] = 1,0,
                                    ["managed"] = {
                                    },
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame",
                                },
                            },
                            ["tls"] = 960,0,
                            ["type"] = "WSplitSplit",
                            ["dir"] = "horizontal",
                        },
                        ["bottom"] = true,
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<4>",
                    },
                },
                ["type"] = "WGroupWS",
                ["name"] = "prod_srv",
            },
            [4] = {
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<28>",
                ["geom"] = {
                    ["w"] = 1920,0,
                    ["h"] = 1200,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["level"] = 1025,0,
                        ["sizepolicy"] = "free_glue",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 360,0,
                            ["x"] = 640,0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*<28>",
                    },
                },
            },
        },
        ["type"] = "WScreen",
        ["name"] = "WScreen",
    },
}

